project_id = "qlvcirkyharrarblgdue"

[functions.status-reminder]
verify_jwt = false

[functions.auto-refund]
verify_jwt = false

[functions.shufti-verify]
verify_jwt = false

[functions.shufti-webhook]
verify_jwt = false

[functions.moderate-message]
verify_jwt = false