project_id = "qlvcirkyharrarblgdue"

[functions.status-reminder]
verify_jwt = false

[functions.auto-refund]
verify_jwt = false

[functions.shufti-verify]
verify_jwt = false

[functions.shufti-webhook]
verify_jwt = false

[functions.moderate-message]
verify_jwt = false

[functions.send-invoice-email]
verify_jwt = false

[functions.paystack-webhook]
verify_jwt = false

[functions.initialize-payment]
verify_jwt = false

[functions.send-sms-otp]
verify_jwt = false

[functions.verify-sms-otp]
verify_jwt = false

[functions.reset-password-otp]
verify_jwt = false

[functions.notify-helpers-new-job]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.delete-account]
verify_jwt = false